@startuml BookSystem
package "Book System" {
    
    ' Define main interfaces
    
    interface IBookRepository {
        + addBook()
        + updateBook()
        + removeBook()
        + listBooksByGenre()
        + CheckAvailability()
    }
    
    ' Define main classes

    class BookRepository implements IBookRepository  {
        - _books: List<Book>
        + AddBook(book: Book)
        + UpdateBook()
        + RemoveBook(title: string)
        + ListBooksByGenre(genre: string)
        + CheckAvailability(title: string)
        + FoundBookByTitle(title: string): Book
        + AvailableBooks()
        + GetBooksList(): List<Book>
        + SetBooksList(books: List<Book>)
    }

    class Book {
        - title: String
        - author: String
        - ISBN: String
        - genre: String
        - publicationYear: Date
    }
    
}
@enduml 