@startuml FineSystem
package "Fine System" {
    
    ' Define main classes

    class FineManager {
        - LogService : ILogService
        - List : Fines
        + AddFine()
        + ShowFines()
        + FinesFromUser()
    }

    class Fine {
        - Paid: bool
        - Borrow: Borrow
        - Cost : int
        + CalculateFine()
        + FineDetails()
    }
}
@enduml 