@startuml LibraryManagementSystem
package "Library system"{
    ' Define modules
    !include UserSystem.puml
    !include ReportSystem.puml
    !include BorrowSystem.puml
    !include BookSystem.puml
    !include SearchSystem.puml
    !include FineSystem.puml
    !include UI.puml
    !include StatisticSystem.puml
    !include ReturnSystem.puml
    !include ErrorHandling.puml
    !include ExceptionHandling.puml

    ' Define classes

    class Library {
        - PatronManager patronManager
        - StaffManager staffManager
        - BorrowManager borrowManager
        - BookRepository bookRepository
        - FinesManager FinesManager
        + InitializeProgram()
    }

    ' Define relationships
    Library ..* PatronManager
    Library ..* StaffManager
    Library ..* BorrowManager
    Library ..* BookRepository
    Library ..* FineManager
    FineManager ..* Fine
    PatronSearch ..* PatronManager
    BookSearch ..* BookRepository
    Borrow ..* Book
    Borrow ..* PatronConcrete
    BorrowManager ..* Borrow
    UserCreator ..> User
    Library ..> HomePageMenu
    HomePageMenu ..> Login
    Login ..> PatronMenu
    PatronMenu ..> PatronSearchMenu
    PatronMenu ..> PatronBorrowMenu
    PatronMenu ..> ReturnContext : uses
    PatronMenu *.. PatronReturnMenu : has
    StaffMenu ..> BookStaffManagement
    StaffMenu ..> ReportStaffMenu
    StaffMenu ..> StaffSearchMenu
    Login ..> StaffMenu
    ABorrowReport ..* BorrowManager
    APatronReport ..* PatronManager
    PatronManager ..* PatronConcrete
    StaffManager ..* StaffConcrete
    BookRepository ..* Book
    PatronSearchMenu ..> MenuGenerator
    PatronBorrowMenu ..> MenuGenerator
    ReportStaffMenu ..> MenuGenerator
    StaffSearchMenu ..> MenuGenerator
    BookStaffManagement ..> MenuGenerator
    PatronMenu ..> MenuGenerator
    StaffMenu ..> MenuGenerator
    PatronSearchMenu ..> PerformSearch
    StaffSearchMenu ..> PerformSearch
    PerformSearch ..> SearchBase
    Statistic ..> StatisticReport
    ReportStaffMenu ..> Statistic
    ReturnContext o-- Borrow
    ReturnContext o-- Fine

    GlobalException <|-- BookNotFoundException
    GlobalException <|-- PatronNotFoundException
    GlobalException --> Severity
    ILogService --> Severity

    PatronSearch ..> BookNotFoundException
    BookSearch ..> PatronNotFoundException
}
@enduml
