@startuml ReportSystem

package "Report System" {
    ' Define main contract
    interface IReport {
        + GenerateReport() : void
    }

    ' Define main abstract base
    abstract class BaseReport implements IReport {
        - BorrowManager : _borrowManager
    }

    ' Define main classes
    class BorrowPatronHistory extends BaseReport {
        + PatronBorrowHistoryReport() : void
    }

    class CurrentBorrowBooksReport extends BaseReport {
        + BorrowedBooksReport() : void
    }

    class OverdueBooksReport extends BaseReport {
        + OverdueBooksListReport() : void
    }
}

@enduml
